config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :jets, only: [:index, :new, :create, :show] do
    resources :bookings, only: [:new, :create, :index]
  end
  patch "/bookings/:id/accept", to: "bookings#accept", as: "accept"
  patch "/bookings/:id/reject", to: "bookings#reject", as: "reject"
  get "/dashboard", to: "users#show", as: "dashboard"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :jet

  validates :status, inclusion: { in: %w(accepted pending rejected) }
end

app/models/jet.rb
class Jet < ApplicationRecord
  belongs_to :user
  geocoded_by :city
  after_validation :geocode, if: :will_save_change_to_city?
  has_many :bookings
  has_one_attached :photo
  validates :name, presence: true
  validates :description, presence: true, length: { minimum: 10 }
  validates :country, presence: true
  validates :city, presence: true
  validates :price, presence: true, numericality: { only_integer: true }
  validates :photo, presence:true
end

app/models/user.rb
class User < ApplicationRecord

  has_many :bookings
  has_many :jets
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_jet, only: [:new, :create]

  def index
    @bookings = Booking.all
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)

    @start_date = booking_params[:start_date].split(" to ")[0].to_date
    @end_date = booking_params[:start_date].split(" to ")[1].to_date

    @booking.start_date = @start_date
    @booking.end_date = @end_date

    @booking.jet = @jet
    @booking.user = current_user
    if @booking.save
      redirect_to dashboard_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def accept
    @booking = Booking.find(params[:id])
    @booking.status = "accepted"
    @booking.save
    redirect_to dashboard_path
  end
  def reject
    @booking = Booking.find(params[:id])
    @booking.status = "rejected"
    @booking.save
    redirect_to dashboard_path
  end

  private

  def set_jet
    @jet = Jet.find(params[:jet_id])
  end

  def booking_params
    params.require(:booking).permit(:status, :start_date)
  end
end

app/controllers/jets_controller.rb
class JetsController < ApplicationController
  before_action :set_jet, only: [:show]

  def index
    @jets = Jet.all
    count = 0
    current_user.jets.each do |jet|
      count += jet.bookings.count { |booking| booking.status == "pending" }
    end
    @bookings_pending = count
    if params[:query].present?
      sql_subquery = "city @@ :query OR country @@ :query"
      @jets = @jets.where(sql_subquery, query: "%#{params[:query]}%")
    end
  end

  def show
    @marker = { lat: @jet.latitude, lng: @jet.longitude }
    @booking = Booking.new
    count = 0
    current_user.jets.each do |jet|
      count += jet.bookings.count { |booking| booking.status == "pending" }
    end
    @bookings_pending = count
  end

  def new
    @jet = Jet.new
    count = 0
    current_user.jets.each do |jet|
      count += jet.bookings.count { |booking| booking.status == "pending" }
    end
    @bookings_pending = count
  end

  def create
    @jet = Jet.new(jet_params)
    @jet.user = current_user
    if @jet.save
      redirect_to jet_path(@jet), notice: 'jet was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
  def set_jet
    @jet = Jet.find(params[:id])
  end
  def jet_params
    params.require(:jet).permit(:name, :description, :price, :user_id, :photo, :city, :country)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    if current_user
      count = 0

      current_user.jets.each do |jet|
        count += jet.bookings.count { |booking| booking.status == "pending" }
      end
      @bookings_pending = count
    end 
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    @jets = current_user.jets
    @bookings = current_user.bookings
    count = 0

    current_user.jets.each do |jet|
      count += jet.bookings.count { |booking| booking.status == "pending" }
    end
    @bookings_pending = count
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<%= link_to "My bookings", jet_bookings_path %>

  <% @bookings.each do |booking| %>
    <ul>
      <li>
        <%= booking.status%>
        <%= booking.jet.name %>
        <%= booking.user.first_name %>
      </li>
    </ul>
  <% end %>

app/views/bookings/new.html.erb
<h1>New booking</h1>

<%= simple_form_for [@jet, @booking] do |f| %>

  <%= f.input :start_date,
              label: 'Booking Date',
              as: :string,
              input_html: { data: { controller: "datepicker" } } %>
  <%= f.submit "Submit booking", class: "btn btn-dark" %>
<% end %>

app/views/jets/_form.html.erb
<div class="container-form">
  <h1 class="h1-form">New jet</h1>

  <%= simple_form_for(@jet) do |f| %>
    <div class="form-inputs">
      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.input :country , as: :string%>
      <%= f.input :city %>
      <%= f.input :price, label: 'Daily Price in €' %>
      <%= f.input :photo, as: :file %>
    </div>
    <div class="form-actions">
      <%= f.submit "Submit jet", class: "btn btn-dark" %>
    </div>
  <% end %>
</div>

app/views/jets/index.html.erb
<div class="container-index">
  <h1 class="h1-index">All Available Jets</h1>

  <div class="row justify-content-center">
    <div class="col-lg-12 my-3" data-controller="reset-form">
      <%= form_with url: jets_path, method: :get, class: "d-flex" do %>
          <%= text_field_tag :query,
                params[:query],
                class: "form-control",
                placeholder: "Search...",
                data: {reset_form_target: "text"}
          %>
        <%# <div data-action="click->reset-form#reset"> %>
        <%= submit_tag "Where?", city: "", class: "btn btn-dark", data: {action: "click->reset-form#reset"} %>
        <%# </div> %>
      <% end %>
    </div>
  </div>



  <div class="cards">
    <% if @jets.any? %>
      <% @jets.sort_by {|jet| jet.price }.each do |jet| %>
        <%= link_to jet_path(jet) do %>
            <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path jet.photo.key, height: 300, crop: :fill %>')">
              <%= jet.name %>
              <div class="city-location"><i class="fa-solid fa-location-dot" style="color: #f4f4f4;"></i> <%= jet.city %></div>
              <div class="city-price"><%= jet.price.to_s.reverse.scan(/\d{1,3}/).join(",").reverse%>€/day</div>
            </div>
        <% end %>
    <% end %>
      <% else %>
      <h2>Sorry, no Jets Found.</h2>
    <% end %>
  </div>
</div>

app/views/jets/new.html.erb
<%= render "form", jet: @jet %>

app/views/jets/show.html.erb
<div class="container-show">
  <div class="card-trip">
    <% if @jet.photo.attached? %>
      <img src= <%= cl_image_path @jet.photo.key, crop: :fill %> />
    <% else  %>
      <img src='https://images.unsplash.com/photo-1619652116813-98504fce82d2?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8cHJpdmF0ZSUyMGpldHxlbnwwfHwwfHx8MA%3D%3D'/>
    <% end %>
    <div class="card-trip-infos">
          <div>
            <h2><%= @jet.name %></h2>
            <p><%= @jet.description %></p>
            <p><%= @jet.country %> - <%= @jet.city %></p>
            <p>Owned by: <%= @jet.user.first_name %> <%= @jet.user.last_name %></p>
          </div>
          <h2 class="card-trip-pricing"> <%= @jet.price.to_s.reverse.scan(/\d{1,3}/).join(",").reverse  %>€/day</h2>
    </div>
  </div>
  <div style="width: 70%; height: 502px;"
    data-controller="map"
    data-map-marker-value="<%= @marker.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
  <div data-controller="toggle" class="mt-5">
   <button data-action="click->toggle#booking" class="btn btn-dark">New Booking</button>
    <div data-toggle-target="button" class="d-none mt-2">
      <%= simple_form_for [@jet, @booking] do |f| %>
        <%= f.input :start_date,
                    label: 'Booking Date',
                    as: :string,
                    input_html: { data: { controller: "datepicker" } } %>
        <%= f.submit "Book", class: "btn btn-secondary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirBnbJets</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "shared/flashes" %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container-home">
  <div class="main w-100 m-0 d-flex">
    <div class="main-image">
      <%= image_tag("jet2.jpg", class:"home-image") %>
    </div>

  <div class="home-card">
    <div class="main-info area" >
      <h1 id="margin" class= "ms-5">Fly</h1>
      <h1 class="ms-5">With</h1>
      <h1 class="ms-5">Style</h1>
      <div class="height">
      <%= link_to "Get Started", jets_path, class: "button ms-5" %>
      </div>
      </div>
  </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-new">
    <p><i class="fa-solid fa-copyright" style="color: #bfbdbd;"></i> 2023 All rights reserved.</p>
  </div>
  <div class="footer-copyright">
    <p><i class="fa-solid fa-location-dot" style="color: #bfbdbd;"></i> Av. da Pedra Verde, 90 Matosinhos</p>
    <p><i class="fa-solid fa-phone" style="color: #bfbdbd;"></i></i> +351 912 345 678</p>
    <p><i class="fa-solid fa-envelope" style="color: #bfbdbd;"></i></i> jetbnb@lewagon.com</p>
  </div>
</div>

</footer>

<style>
.footer {
  background: #e0dede;
  display: flex;
  align-items: center;
  justify-content: space-between;
  clear: both;
  height: 125px;
  padding: 0px 50px;
  color: rgba(0,0,0,0.3);
}

.footer-links {
  display: flex;
  align-items: center;
}
.footer-links a {
  color: black;
  opacity: 0.15;
  text-decoration: none;
  font-size: 24px;
  padding: 0px 10px;
}
.footer-links a:hover {
  opacity: 1;
}

.footer-copyright {
   line-height: 0.8px;
}
</style>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCGZ2b0YHmwnyR-1XF5ctsKNDHeBlspziRHQ&usqp=CAU" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "/", class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "All Jets", "/jets", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Dashboard", "/dashboard", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <% if current_user %>
                <div class="notification-bell d-flex align-items-center">
                  <% if @bookings_pending != 0 %>
                    <div><i class="fa-solid fa-bell"></i></div>
                    <div><%= link_to  "#{@bookings_pending}", "/dashboard", class: "nav-link" %></div>
                  <% end %>
                </div>
            <% end %>
          </li>
          <li class="nav-item dropdown">
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= image_tag "https://upload.wikimedia.org/wikipedia/commons/9/99/Sample_User_Icon.png", class: "avatar", alt: "dropdown menu" %>
            </a>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "Action", "#", class: "dropdown-item" %>
                <%= link_to "Another action", "#", class: "dropdown-item" %>
                <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
              </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container-dash">
  <h1 class="h1-dash">Welcome <%= current_user.first_name %> To Your Dashboard</h1>

  <h2 class="h2-dash">All Of Your Available Jets</h2>
  <% unless @jets.empty? %>
    <div class="cards-show">
      <% @jets.each do |jet| %>
        <%= link_to jet_path(jet) do %>
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path jet.photo.key, height: 300, crop: :fill %>')">
            <%= jet.name %>
          </div>
         <% end %>
      <% end %>
    </div>
  <% end %>

  <h2 class="h2-dash">Manage The Bookings Of Your Jets:</h2>
    <% @jets.each do |jet| %>
      <% jet.bookings.each do |booking| %>
        <div class="card-booking">
            <h5><i class="fa-solid fa-user" style="color: #494949;"></i> <%= booking.user.first_name %> <%= booking.user.last_name %></h5>
            <h6>Wants to rent your <%= booking.jet.name %></h6>
            <p>From <%= booking.start_date.strftime('%d/%m/%Y') %> to <%= booking.end_date.strftime('%d/%m/%Y') %>. The total price is: <%= ((booking.end_date - booking.start_date).to_i * jet.price).to_s.reverse.scan(/\d{1,3}/).join(",").reverse %>€. Current status from this booking: <strong><%= booking.status %></strong>.</p>
            <% if booking.status == "pending" %>
              <p> You want to: <%= link_to "Accept", accept_path(booking), data: {turbo_method: :patch}  %> or <%= link_to "Reject", reject_path(booking), data: {turbo_method: :patch} %> ?</p>
             <% else %>
              <p><i class="fa-solid fa-envelope-circle-check" style="color: #494949;"></i> The requester will receive an email about your decision. </p>
            <% end %>
        </div>
      <% end %>
    <% end %>

  <h2 class="h2-dash">Check The Status Of Your Next Flights:</h2>
  <% @bookings.each do |booking| %>
    <div class="card-booking-mine">
      <ul>
        <p><i class="fa-solid fa-calendar-check" style="color: #494949;"></i> Your booking of a <%= booking.jet.name %>, from  <%= booking.start_date.strftime('%d/%m/%Y') %> to <%= booking.end_date.strftime('%d/%m/%Y') %> is: <strong><%= booking.status %></strong>.</p>
        <p>The total price is: <%= ((booking.end_date - booking.start_date).to_i * booking.jet.price).to_s.reverse.scan(/\d{1,3}/).join(",").reverse %>€.</p>
      </ul>
    </div>
  <% end %>

   <h2 class="h2-dash" >Interested In Leasing Out Your Jet?</h2>
  <div class="creation">
    <%= link_to "Add a Jet", new_jet_path %>
  </div>
</div>